# These are supported funding model platforms

github: Natizyskunk
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ['https://www.buymeacoffee.com/Natizyskunk', 'https://www.paypal.com/donate?business=DELD7APHHM3BC&no_recurring=0&currency_code=EUR', 'https://paypal.me/natanfourie']
